# .readthedocs.yml
# Read the Docs 配置文件
# 各位贡献者请不要修改此文件，谢谢配合！

# Required
version: 2

# conf.py 配置文件位置
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs（用不上）
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF
formats: [
 #- pdf
]

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.8  #改成3.8
  install:
    - requirements: docs/requirements.txt #requirements 文件位置
